/*
 * GenppscriptBuilder.java
 */

// COPYRIGHT_BEGIN
//
// The MIT License (MIT)
//
// Copyright (c) 2000-2020 Wizzer Works
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// COPYRIGHT_END

// Declare package.
package com.wizzer.mle.studio.dpp.builder;

// Import standard Java classes.
import java.util.Map;

// Import Eclipse classes.
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.IncrementalProjectBuilder;
import org.eclipse.core.resources.IResourceDelta;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IProgressMonitor;

// Import Magic Lantern Digital Workprint classes.
import com.wizzer.mle.studio.dwp.DwpProjectManager;
import com.wizzer.mle.studio.dpp.DppException;
import com.wizzer.mle.studio.dpp.DppLog;
import com.wizzer.mle.studio.dpp.project.MasteringProjectManager;
import com.wizzer.mle.studio.dpp.properties.GenppscriptPropertyManager;

/**
 * This class is an incremental project builder for the Magic Lantern
 * mastering step, <i>genppscript</i>.
 * 
 * @author Mark S. Millard
 */
public class GenppscriptBuilder extends IncrementalProjectBuilder
{
    /**
     * The default constructor.
     */
    public GenppscriptBuilder()
    {
        super();
    }

    /**
     * Build using the Magic Lantern <i>genppscript</i> command utiltity.
     * 
     * @param kind The kind of build being requested. Valid values are:
     * <ul>
     * <li>FULL_BUILD- indicates a full build.</li>
     * <li>INCREMENTAL_BUILD- indicates an incremental build.</li>
     * <li>AUTO_BUILD- indicates an automatically triggered incremental build (auto-building on).</li>
     * </ul>
     * @param args A table of builder-specific arguments keyed by argument name
     * (key type: <code>String</code>, value type: <code>String</code>);
     * <b>null</b> is equivalent to an empty map.
     * @param monitor A progress monitor, or <b>null</b> if progress reporting and cancellation are not desired.
     * 
     * @return The list of projects for which this builder would like deltas
     * the next time it is run or <b>null</b> if none.
     */
    protected IProject[] build(int kind, Map args, IProgressMonitor monitor)
        throws CoreException
    {
        if (kind == IncrementalProjectBuilder.FULL_BUILD)
        {
            fullBuild(monitor);
        } else
        {
            IResourceDelta delta = getDelta(getProject());
            if (delta == null)
            {
                fullBuild(monitor);
            } else
            {
                incrementalBuild(delta, monitor);
            }
        }
        return null;
    }

    /**
     * Perform a full build on the project.
     * 
     * @param monitor A progress monitor to use during the build.
     * 
     * @throws CoreException This exception is thrown if an error occurs
     * while running <i>genppscript</i>.
     */
    protected void fullBuild(final IProgressMonitor monitor) throws CoreException
    {
        try
        {
            getProject().accept(new GenppscriptBuildVisitor(monitor));
        } catch (CoreException ex)
        {
            DppLog.logError(ex,"Error occurred while performing a full build.");
        }
    }

    /**
     * Perform an incremental build on the project.
     * 
     * @param delta The delta of resources.
     * @param monitor A progress monitor to use during the build.
     * 
     * @throws CoreException This exception is thrown if an error occurs
     * while running <i>genppscript</i>.
     */
    protected void incrementalBuild(IResourceDelta delta, IProgressMonitor monitor)
        throws CoreException
    {
         // The visitor does the work.
         delta.accept(new GenppscriptIncrementalBuildVisitor(monitor));
    }

    /**
     * Remove the derived assets generated by <i>genppscript</i>.
     *
     * @param monitor A progress monitor to use during the build.
     */
    protected void clean(IProgressMonitor monitor)
    {
    	IProject project = getProject();
    	
    	try
    	{
    	    String destDir = MasteringProjectManager.getInstance().getDestinationDirValue(project);
    	    
    	    // Remove the generated script file.
    	    String script = GenppscriptPropertyManager.getInstance().getScriptValue(project);
    	    String filename = new String(destDir + "/" + script);
    	    IFile file = project.getFile(filename);
    	    file.delete(true,false,monitor);
    	    
    	    // Remove the generated TOC file.
    	    String toc = GenppscriptPropertyManager.getInstance().getTocValue(project);
    	    if (DwpProjectManager.getInstance().isJavaProject(project))
    	    {
    	        filename = new String(destDir + "/" + toc + ".java");
        	    file = project.getFile(filename);
        	    file.delete(true,false,monitor);
    	    } else
    	    {
    	    	// Remove source file.
    	    	filename = new String(destDir + "/" + toc + ".cxx");
        	    file = project.getFile(filename);
        	    file.delete(true,false,monitor);
        	    
        	    // Remove header file.
    	    	filename = new String(destDir + "/" + toc + ".h");
        	    file = project.getFile(filename);
        	    file.delete(true,false,monitor);
    	    }
    	} catch (DppException ex)
    	{
    		DppLog.logError(ex,"Error occurred while performing a clean.");
    	} catch (CoreException ex)
    	{
    		DppLog.logError(ex,"Error occurred while deleting genppscript artifacts.");
    	}
     }

}
