/*
 * ResourceBuilder.java
 * Created on Feb 5, 2008
 */

// COPYRIGHT_BEGIN
//
//  Copyright (C) 2000-2008  Wizzer Works
//
//  Wizzer Works makes available all content in this file ("Content").
//  Unless otherwise indicated below, the Content is provided to you
//  under the terms and conditions of the Common Public License Version 1.0
//  ("CPL"). A copy of the CPL is available at
//
//      http://opensource.org/licenses/cpl1.0.php
//
//  For purposes of the CPL, "Program" will mean the Content.
//
//  For information concerning this Makefile, contact Mark S. Millard,
//  of Wizzer Works at msm@wizzerworks.com.
//
//  More information concerning Wizzer Works may be found at
//
//      http://www.wizzerworks.com
//
// COPYRIGHT_END

// Declare package.
package com.wizzer.mle.studio.android.dpp;

// Import standard Java classes.
import java.util.Map;

// Import Eclipse classes.
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IncrementalProjectBuilder;
import org.eclipse.core.resources.IResourceDelta;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IProgressMonitor;

// Import Magic Lantern Digital Workprint classes.
import com.wizzer.mle.studio.dpp.DppLog;

/**
 * This class is an incremental project builder for the Magic Lantern
 * mastering step, <i>gendpp</i>. It copies the generated Digital Playprint
 * to the Android resource folder <i>res/raw</i> and renames it to <i>playprint.dpp</i>.
 * 
 * @author Mark S. Millard
 */
public class ResourceBuilder extends IncrementalProjectBuilder
{
	/** The Android resource directory. */
	public static final String PLAYPRINT_RESOURCE_DIR = "res/raw";
	/** The Android resource. */
	public static final String PLAYPRINT_FILENAME = "playprint.dpp";

    /**
     * The default constructor.
     */
    public ResourceBuilder()
    {
        super();
    }

    /**
     * Copy the Digital Playprint generated by <i>gendpp</i> to the Android resource
     * directory <i>res/raw</i>.
     * 
     * @param kind The kind of build being requested. Valid values are:
     * <ul>
     * <li>FULL_BUILD- indicates a full build.</li>
     * <li>INCREMENTAL_BUILD- indicates an incremental build.</li>
     * <li>AUTO_BUILD- indicates an automatically triggered incremental build (auto-building on).</li>
     * </ul>
     * @param args A table of builder-specific arguments keyed by argument name
     * (key type: <code>String</code>, value type: <code>String</code>);
     * <b>null</b> is equivalent to an empty map.
     * @param monitor A progress monitor, or <b>null</b> if progress reporting and cancellation are not desired.
     * 
     * @return The list of projects for which this builder would like deltas
     * the next time it is run or <b>null</b> if none.
     */
    protected IProject[] build(int kind, Map args, IProgressMonitor monitor)
        throws CoreException
    {
        if (kind == IncrementalProjectBuilder.FULL_BUILD)
        {
            fullBuild(monitor);
        } else
        {
            IResourceDelta delta = getDelta(getProject());
            if (delta == null)
            {
                fullBuild(monitor);
            } else
            {
                incrementalBuild(delta, monitor);
            }
        }
        return null;
    }

    /**
     * Perform a full build on the project.
     * 
     * @param monitor A progress monitor to use during the build.
     * 
     * @throws CoreException This exception is thrown if an error occurs
     * while copying the Digital Playprint.
     */
    protected void fullBuild(final IProgressMonitor monitor) throws CoreException
    {
        try
        {
            getProject().accept(new ResourceBuildVisitor(monitor));
        } catch (CoreException ex)
        {
            DppLog.logError(ex,"Error occurred while performing a full build.");
        }
    }

    /**
     * Perform an incremental build on the project.
     * 
     * @param delta The delta of resources.
     * @param monitor A progress monitor to use during the build.
     * 
     * @throws CoreException This exception is thrown if an error occurs
     * while copying the Digital Playprint.
     */
    protected void incrementalBuild(IResourceDelta delta, IProgressMonitor monitor)
        throws CoreException
    {
         // The visitor does the work.
         delta.accept(new ResourceIncrementalBuildVisitor(monitor));
    }

    /**
     * Remove the derived assets generated by this builder.
     *
     * @param monitor A progress monitor to use during the build.
     */
    protected void clean(IProgressMonitor monitor)
    {
    	IProject project = getProject();
    	
    	try
    	{
    		// Remove the copied Digital Playprint.
    	    String filename = new String(PLAYPRINT_RESOURCE_DIR + "/" + PLAYPRINT_FILENAME);
    	    IFile file = project.getFile(filename);
    	    file.delete(true,false,monitor);
    	} catch (CoreException ex)
    	{
    		DppLog.logError(ex,"Error occurred while deleting resource artifacts.");
    	}
     }

}
