//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.22 at 03:48:53 PM MST 
//


package com.wizzer.mle.studio.project.metadata.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * User specified meta data.
 * 
 * <p>Java class for user_data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="user_data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;group ref="{http://www.wizzerworks.com/MLE/MetaDataSchema}extension"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user_data", propOrder = {
    "nameAndIdAndAuthor"
})
public class UserData {

    @XmlElementRefs({
        @XmlElementRef(name = "data", namespace = "http://www.wizzerworks.com/MLE/MetaDataSchema", type = JAXBElement.class),
        @XmlElementRef(name = "contact", namespace = "http://www.wizzerworks.com/MLE/MetaDataSchema", type = JAXBElement.class),
        @XmlElementRef(name = "id", namespace = "http://www.wizzerworks.com/MLE/MetaDataSchema", type = JAXBElement.class),
        @XmlElementRef(name = "author", namespace = "http://www.wizzerworks.com/MLE/MetaDataSchema", type = JAXBElement.class),
        @XmlElementRef(name = "name", namespace = "http://www.wizzerworks.com/MLE/MetaDataSchema", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> nameAndIdAndAuthor;

    /**
     * Gets the value of the nameAndIdAndAuthor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameAndIdAndAuthor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameAndIdAndAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getNameAndIdAndAuthor() {
        if (nameAndIdAndAuthor == null) {
            nameAndIdAndAuthor = new ArrayList<JAXBElement<?>>();
        }
        return this.nameAndIdAndAuthor;
    }

}
